In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset["classification_yes"].value_counts()
#refer how many class classified
#to find balanced or imbalanced
#unique entry &counts---->(0-143,1-143)->balanced
#(0-257,1-143)->imbalanced

1    249
0    150
Name: classification_yes, dtype: int64

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', ]]
dep=dataset["classification_yes"]

In [9]:
indep.shape#400-length ,3-i/p column

(399, 27)

In [10]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: uint8

In [11]:
#split into training & test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [12]:
#replace regression to classifier for classification
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid={'criterion':['gini','entropy'],'max_features': ['auto','sqrt','log2'],'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestClassifier(),param_grid,refit=True,verbose=3,n_jobs=1,scoring='f1_weighted')
#f1_weighted suitable for all balanced &imbalance including precision,recall)
#fitting model for grid search
grid.fit(x_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END criterion=gini, max_features=auto, n_estimators=10;, score=0.982 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=auto, n_estimators=10;, score=0.964 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=auto, n_estimators=10;, score=0.947 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=auto, n_estimators=10;, score=0.964 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=auto, n_estimators=10;, score=1.000 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=auto, n_estimators=100;, score=1.000 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=auto, n_estimators=100;, score=0.964 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=auto, n_estimators=100;, score=0.947 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=auto, n_estimators=100;, score=0.964 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=auto, n_estimators=100;, score=1.000 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=sqrt, n_estimators=10;, score=1.000 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=sqrt, n_estimators=10;, score=0.929 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=sqrt, n_estimators=10;, score=0.930 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=sqrt, n_estimators=10;, score=0.964 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=sqrt, n_estimators=10;, score=1.000 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=sqrt, n_estimators=100;, score=1.000 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=sqrt, n_estimators=100;, score=0.945 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=sqrt, n_estimators=100;, score=0.947 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=sqrt, n_estimators=100;, score=0.964 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=sqrt, n_estimators=100;, score=0.982 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=log2, n_estimators=10;, score=0.982 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=log2, n_estimators=10;, score=0.982 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=log2, n_estimators=10;, score=0.947 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=log2, n_estimators=10;, score=0.982 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=log2, n_estimators=10;, score=1.000 total time=   0.0s
[CV 1/5] END criterion=gini, max_features=log2, n_estimators=100;, score=1.000 total time=   0.0s
[CV 2/5] END criterion=gini, max_features=log2, n_estimators=100;, score=0.982 total time=   0.0s
[CV 3/5] END criterion=gini, max_features=log2, n_estimators=100;, score=0.947 total time=   0.0s
[CV 4/5] END criterion=gini, max_features=log2, n_estimators=100;, score=0.982 total time=   0.0s
[CV 5/5] END criterion=gini, max_features=log2, n_estimators=100;, score=1.000 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=auto, n_estimators=10;, score=1.000 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=auto, n_estimators=10;, score=0.946 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=auto, n_estimators=10;, score=0.947 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=auto, n_estimators=10;, score=0.964 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=auto, n_estimators=10;, score=1.000 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=auto, n_estimators=100;, score=1.000 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=auto, n_estimators=100;, score=0.928 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=auto, n_estimators=100;, score=0.947 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=auto, n_estimators=100;, score=0.964 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=auto, n_estimators=100;, score=1.000 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=sqrt, n_estimators=10;, score=0.982 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=sqrt, n_estimators=10;, score=0.928 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=sqrt, n_estimators=10;, score=0.982 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=sqrt, n_estimators=10;, score=0.982 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=sqrt, n_estimators=10;, score=0.982 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=sqrt, n_estimators=100;, score=1.000 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=sqrt, n_estimators=100;, score=0.945 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=sqrt, n_estimators=100;, score=0.930 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=sqrt, n_estimators=100;, score=0.982 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=sqrt, n_estimators=100;, score=0.982 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=log2, n_estimators=10;, score=0.965 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=log2, n_estimators=10;, score=0.982 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=log2, n_estimators=10;, score=0.982 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=log2, n_estimators=10;, score=0.982 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=log2, n_estimators=10;, score=1.000 total time=   0.0s
[CV 1/5] END criterion=entropy, max_features=log2, n_estimators=100;, score=1.000 total time=   0.0s
[CV 2/5] END criterion=entropy, max_features=log2, n_estimators=100;, score=0.982 total time=   0.0s
[CV 3/5] END criterion=entropy, max_features=log2, n_estimators=100;, score=0.965 total time=   0.0s
[CV 4/5] END criterion=entropy, max_features=log2, n_estimators=100;, score=0.982 total time=   0.0s
[CV 5/5] END criterion=entropy, max_features=log2, n_estimators=100;, score=1.000 total time=   0.0s

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1_weighted', verbose=3)

In [13]:
#print best parameter after tuning
#print(grid.best_params_)

re = grid.cv_results_

# Making predictions on the test data using the best estimator found by GridSearchCV

In [14]:

grid_predictions=grid.predict(x_test)

In [15]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)#optional

f1_macro value for best parameter{'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}: 0.9833333333333335

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [17]:
# 79,0 correct diagonal,41,0 wrong diagonal
#type1 error should low
print(cm)

[[44  1]
 [ 1 74]]

In [18]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [19]:
#overall performance(accuracy)=0.89
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        45
           1       0.99      0.99      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

In [20]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])#receiver operating chareteristics area under curve(roc_auc)

0.9997037037037038

In [21]:
table = pd.DataFrame.from_dict(re)

In [22]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009115,0.006213,0.002043,0.003138,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.982221,0.964286,0.947015,0.964286,1.000000,0.971561,0.018060,6
1,0.055678,0.006764,0.010346,0.009161,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",1.000000,0.963889,0.947015,0.964286,1.000000,0.975038,0.021314,5
2,0.012802,0.007188,0.003818,0.002563,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.928571,0.929513,0.964286,1.000000,0.964474,0.031735,12
3,0.068190,0.025363,0.015104,0.003342,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.945469,0.947015,0.964286,0.981728,0.967700,0.020851,11
4,0.009432,0.002151,0.004546,0.003086,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.982221,0.982051,0.947015,0.982051,1.000000,0.978668,0.017277,4
5,0.063601,0.009074,0.006168,0.006031,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.982051,0.947015,0.982051,1.000000,0.982223,0.019348,2
6,0.011224,0.005946,0.003283,0.003356,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",1.000000,0.946153,0.947015,0.963889,1.000000,0.971411,0.024184,7
7,0.064185,0.010285,0.006110,0.006484,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",1.000000,0.927778,0.947015,0.964286,1.000000,0.967816,0.028705,9
8,0.009599,0.005327,0.005054,0.005400,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.982221,0.927778,0.982221,0.982051,0.981728,0.971200,0.021712,8
9,0.061671,0.006205,0.009956,0.006094,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.945469,0.929513,0.982051,0.981728,0.967752,0.026071,10
10,0.011539,0.003681,0.001948,0.002601,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.964572,0.982221,0.982221,0.982051,1.000000,0.982213,0.011204,3
11,0.061506,0.004697,0.008185,0.009153,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.982051,0.964572,0.982051,1.000000,0.985735,0.013281,1

In [23]:
age=int(input("Age:"))
bp=int(input("bp:"))
al=int(input("al:"))
su=int(input("su:"))
bgr=int(input("bgr:"))
bu=int(input("bu:"))
sc=int(input("sc:"))
sod=int(input("sod:"))
pot=int(input("pot:"))
hrmo=int(input("hrmo:"))
pcv=int(input("pcv:"))
wc=int(input("wc:"))
rc=int(input("rc:"))
sg_b=int(input("sg_b:"))
sg_c=int(input("sg_c:"))
sg_d=int(input("sg_d:"))
sg_e=int(input("sg_e:"))
rbc_normal=int(input("rbc_normal:"))
pc_normal=int(input("pc_normal:"))
pcc_present=int(input("pcc_present:"))
ba_present=int(input("ba_present:"))
htn_yes=int(input("htn_yes:"))
dm_yes=int(input("dm_yes:"))
cad_yes=int(input("cad_yes:"))
appet_yes=int(input("appet_yes:"))
pe_yes=int(input("pe_yes:"))
ane_yes=int(input("ane_yes:"))

Age:11
bp:222
al:1
su:1
bgr:22
bu:33
sc:22
sod:11
pot:33
hrmo:44
pcv:55
wc:66
rc:77
sg_b:44
sg_c:33
sg_d:22
sg_e:33
rbc_normal:1
pc_normal:1
pcc_present:1
ba_present:0
htn_yes:0
dm_yes:0
cad_yes:0
appet_yes:0
pe_yes:1
ane_yes:0

In [24]:
Future_Prediction=grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo,pcv,
       wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal, pc_normal,
    pcc_present, ba_present, htn_yes, dm_yes, cad_yes,appet_yes, pe_yes, ane_yes]])
print("Future_Prediction{}".format(Future_Prediction))

Future_Prediction[1]

C:\anaconda\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

In [25]:
import pickle
filename="finalized_model_Grid.sav"
pickle.dump(grid,open(filename,'wb'))

In [27]:
loaded_model=pickle.load(open("finalized_model_Grid.sav",'rb'))
result=loaded_model.predict([[36,111,23,34,55,66,44,22,22,11,11,222,111,222,112,1,1,1,0,0,0,0,0,1,1,1,1]])

C:\anaconda\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

In [28]:
 result

array([1], dtype=uint8)