In [1]:
import pandas as pd

In [2]:
pip install --upgrade scikit-learn

Requirement already up-to-date: scikit-learn in c:\anaconda\lib\site-packages (1.0.2)
Requirement already satisfied, skipping upgrade: numpy>=1.14.6 in c:\anaconda\lib\site-packages (from scikit-learn) (1.16.5)
Requirement already satisfied, skipping upgrade: scipy>=1.1.0 in c:\anaconda\lib\site-packages (from scikit-learn) (1.3.1)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in c:\anaconda\lib\site-packages (from scikit-learn) (0.13.2)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in c:\anaconda\lib\site-packages (from scikit-learn) (3.1.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
dataset=pd.read_csv("CKD.csv")

In [4]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset["classification_yes"].value_counts()
#refer how many class classified
#to find balanced or imbalanced
#unique entry &counts---->(0-143,1-143)->balanced
#(0-257,1-143)->imbalanced

1    249
0    150
Name: classification_yes, dtype: int64

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', ]]
dep=dataset["classification_yes"]

In [9]:
indep.shape#400-length ,3-i/p column

(399, 27)

In [10]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: uint8

In [11]:
#split into training & test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [12]:
#replace regression to classifier for classification
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid={'kernel':['rbf'],'C': [2000,3000]}
grid=GridSearchCV(SVC (probability=True),param_grid,refit=True,verbose=3,n_jobs=1,scoring='f1_weighted')
#f1_weighted suitable for all balanced &imbalance including precision,recall)
#fitting model for grid search
grid.fit(x_train,y_train)

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV 1/5] END ................C=2000, kernel=rbf;, score=0.876 total time=   0.0s
[CV 2/5] END ................C=2000, kernel=rbf;, score=0.859 total time=   0.0s
[CV 3/5] END ................C=2000, kernel=rbf;, score=0.842 total time=   0.0s
[CV 4/5] END ................C=2000, kernel=rbf;, score=0.859 total time=   0.0s
[CV 5/5] END ................C=2000, kernel=rbf;, score=0.891 total time=   0.0s
[CV 1/5] END ................C=3000, kernel=rbf;, score=0.911 total time=   0.0s
[CV 2/5] END ................C=3000, kernel=rbf;, score=0.876 total time=   0.0s
[CV 3/5] END ................C=3000, kernel=rbf;, score=0.876 total time=   0.0s
[CV 4/5] END ................C=3000, kernel=rbf;, score=0.858 total time=   0.0s
[CV 5/5] END ................C=3000, kernel=rbf;, score=0.927 total time=   0.0s

GridSearchCV(estimator=SVC(probability=True), n_jobs=1,
             param_grid={'C': [2000, 3000], 'kernel': ['rbf']},
             scoring='f1_weighted', verbose=3)

In [13]:
#print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
grid_predictions=grid.predict(x_test)

In [14]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)#optional

f1_macro value for best parameter{'C': 3000, 'kernel': 'rbf'}: 0.868352974992814

In [15]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [16]:
# 79,0 correct diagonal,41,0 wrong diagonal
#type1 error should low
print(cm)

[[41  4]
 [12 63]]

In [17]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [18]:
#overall performance(accuracy)=0.89
print(clf_report)

              precision    recall  f1-score   support

           0       0.77      0.91      0.84        45
           1       0.94      0.84      0.89        75

    accuracy                           0.87       120
   macro avg       0.86      0.88      0.86       120
weighted avg       0.88      0.87      0.87       120

In [19]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])#receiver operating chareteristics area under curve(roc_auc)

0.9345185185185185

In [20]:
table = pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.018704,0.004955,0.003125,0.006250,2000,rbf,"{'C': 2000, 'kernel': 'rbf'}",0.876368,0.859025,0.841653,0.859025,0.890909,0.865396,0.016830,2
1,0.025904,0.007781,0.003581,0.004478,3000,rbf,"{'C': 3000, 'kernel': 'rbf'}",0.911105,0.876368,0.876368,0.858289,0.927273,0.889881,0.025345,1

In [22]:
age=float(input("Age:"))
bp=float(input("bp:"))
al=float(input("al:"))
su=float(input("su:"))
bgr=float(input("bgr:"))
bu=float(input("bu:"))
sc=float(input("sc:"))
sod=float(input("sod:"))
pot=int(input("pot:"))
hrmo=float(input("hrmo:"))
pcv=float(input("pcv:"))
wc=float(input("wc:"))
rc=float(input("rc:"))
sg_b=float(input("sg_b:"))
sg_c=float(input("sg_c:"))
sg_d=float(input("sg_d:"))
sg_e=float(input("sg_e:"))
rbc_normal=float(input("rbc_normal:"))
pc_normal=float(input("pc_normal:"))
pcc_present=float(input("pcc_present:"))
ba_present=float(input("ba_present:"))
htn_yes=float(input("htn_yes:"))
dm_yes=float(input("dm_yes:"))
cad_yes=float(input("cad_yes:"))
appet_yes=float(input("appet_yes:"))
pe_yes=float(input("pe_yes:"))
ane_yes=float(input("ane_yes:"))

Age:21
bp:122
al:12
su:11
bgr:1
bu:1
sc:1
sod:1
pot:1
hrmo:1
pcv:2
wc:2
rc:2
sg_b:2
sg_c:2
sg_d:2
sg_e:2
rbc_normal:1
pc_normal:1
pcc_present:1
ba_present:0
htn_yes:0
dm_yes:0
cad_yes:0
appet_yes:0
pe_yes:0
ane_yes:0

In [23]:
Future_Prediction=grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo,pcv,
       wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal, pc_normal,
    pcc_present, ba_present, htn_yes, dm_yes, cad_yes,appet_yes, pe_yes, ane_yes]])
print("Future_Prediction{}".format(Future_Prediction))

Future_Prediction[1]

C:\anaconda\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"

In [24]:
import pickle
filename="finalized_model_Grid.sav"
pickle.dump(grid,open(filename,'wb'))

In [25]:
loaded_model=pickle.load(open("finalized_model_Grid.sav",'rb'))
result=loaded_model.predict([[36,111,23,34,55,66,44,22,22,11,11,222,111,222,112,1,1,1,0,0,0,0,0,1,1,1,1]])

C:\anaconda\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"

In [26]:
result

array([1], dtype=uint8)